name: Scan and Install IDs

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor

jobs:
  update-json-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '15.x'

    - name: Install Dependencies
      run: npm install

    - name: Run ID Generation
      run: node update_json_ids.js

    - name: Commit and Push Updates
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git commit -m "Updated JSON files with missing IDs" || echo "No changes to commit"
        git push
